### ISSUE TITLE
not tracks api calls

### ISSUE THREAD

**Issue by GrishinSergey** [adibfara/WatchTower#1]
hello, I tryied to use this util for monitoring my api, but  I see nothing in web browser:
![image](https://user-images.githubusercontent.com/12826416/58413957-b0b0ee80-8082-11e9-8ebd-eccd62d7fec5.png)
I use this util in my project pretty like this:
```java
TowerObserver[] observers = new WebWatchTowerObserver[1];
observers[0] = new WebWatchTowerObserver(8085, 5003);
WatchTower.INSTANCE.start(observers, 100);
```
In logcat I saw `WatchTower started, listening on ....`, but in browser's screen as you see, nothing happen.

So, what can be the reason of this? Thank you for soon answer

**Comment by adibfara** [comment]
Could you either remove the websocket port (the second argument) or set it as 5003 and see If anything changes?
Also if the problem still persists, could you send your browser console logs (F12) here?

Thanks.

**Comment by GrishinSergey** [comment]
As you see, I stubbed second param as 5003. Cuz project on java, I can't remove it, so I stubbed it from sources.

Also, here is the log:
![image](https://user-images.githubusercontent.com/12826416/58418054-59654b00-808f-11e9-8cfb-f4f1a1bbe803.png)

**Comment by adibfara** [comment]
Sorry, there was a typo in my response, I meant could you change the websocket to something else (5004 for example) and see what happens?
I will investigate on a non-Kotlin project (Java) to see if anything fails.

**Comment by adibfara** [comment]
Have you added the required interceptor to your OKHttp builder?

**Comment by GrishinSergey** [comment]
Sorry, man. I rechecked my initialisation of retrofit client, and I really forgot about Interceptor. All works like a charm. Thank you for so cool lib!
