### ISSUE TITLE
WatchTowerInterceptor is not public class

### ISSUE THREAD

**Issue by frakc** [adibfara/WatchTower#4]
this class is not public so it cannot be referenced

**Comment by adibfara** [comment]
It _is_ a public class, are you sure you have imported the dependencies correctly?

**Comment by frakc** [comment]
![Screenshot from 2019-05-31 11-29-07](https://user-images.githubusercontent.com/1126230/58692659-bf0b4d00-8397-11e9-9dd9-7f44f25b42f3.png)

  implementation 'com.snakyapps.watchtower:core:1.0.0'
  debugImplementation 'com.snakyapps.watchtower:interceptor-okhttp:1.0.0'
  releaseImplementation 'com.snakyapps.watchtower:interceptor-okhttp-no-op:1.0.0'


on screenshot you can see that class WatchTower is accessible and Interceptor and observer are not.

import com.snakydesign.watchtower.interceptor.WatchTowerInterceptor
ide highlight interpector package as not accessible to

**Comment by adibfara** [comment]
Could you test it by providing both dependencies as `implementation` just to see if it works?
Something like below:
```groovy
implementation 'com.snakyapps.watchtower:core:1.0.0'
implementation  'com.snakyapps.watchtower:interceptor-okhttp:1.0.0'
```
