### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by abhimuktheeswarar** [adibfara/WatchTower#6]
127.0.0.1 refused to connect.

Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by william-reed** [comment]
Checkout the steps I added in my PR to the readme to help you get it set up https://github.com/adibfara/WatchTower/pull/7

**Comment by abhimuktheeswarar** [comment]
Hi, I tried with the updated steps.
But now, the Watchtower is opening, but no API calls are visible in it. Just blank.

**Comment by william-reed** [comment]
That's progress, are you certain you've added the interceptor properly?

**Comment by abhimuktheeswarar** [comment]
This is how I add it.

```
 OkHttpClient.Builder builder = new OkHttpClient().newBuilder()
                .connectTimeout(120, TimeUnit.SECONDS)
                .writeTimeout(120, TimeUnit.SECONDS)
                .readTimeout(120, TimeUnit.SECONDS)
                .cache(cache)
                .retryOnConnectionFailure(true)
                .addInterceptor(new com.snakydesign.watchtower.interceptor.WatchTowerInterceptor());
```
Below this I add more interceptors:

```
builder.addInterceptor(new ErrorHandlingInterceptor(context))
                .addInterceptor(authInterceptor)
                .addInterceptor(httpLoggingInterceptor);
```

And in the Application class `onCreate()`:

```
if (BuildConfig.DEBUG) {

            TowerObserver[] towerObserverList = new TowerObserver[1];
            towerObserverList[0] = new WebWatchTowerObserver(8085,5003);
            WatchTower.INSTANCE.start(towerObserverList,100);
        }
```

**Comment by adibfara** [comment]
Have you forwarded the ports for the websocket too? since a websocket server will be running on that port, its ports need to be forwarded.

**Comment by adibfara** [comment]
Also, I don't think this is an issue with the library, but with port forwarding in emulator generally.
Please check with a real device and re-open this issue If the problem still persists.
